### ISSUE TITLE
Add a test that we return the correct number of results

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#112]
This is a [bug](https://github.com/rladies/meetupr/issues/111) that could have been found by having a unit test for this.  This ticket is generic, though the bug above is for `find_groups()` specficially.

**Comment by GregSutcliffe** [comment]
I took a pass at this but I'm struggling to get the tests to use my existing `meetup_token` so that I can record the response with `vcr`.

Here's my test:
```
test_that("find_groups() can correctly get 2 pages", {
  vcr::use_cassette("find_groups_pages_2", {
    meetup_auth(token = '/path/to/my/meetupr/.httr-oauth.token')
    groups <- find_groups(text = "Ansible", radius = 'global')
  })
  expect_equal(nrow(groups), 324)
})
```
Which should work (it's what you'd do in the console). But the test fails, reporting:
```
── Error (test-find_groups2.R:5:3): find_groups() can correctly get 2 pages ────
Error: HTTP 400 Bad Request error encountered for: find/groups.
```
And when I look at the recorded YAML from `vcr`, I see (edited for brevity):

```
- request:
    method: get
    uri: https://api.meetup.com/find/groups?offset=0&text=Ansible&topic_id=&fields=&radius=global
  response:
    status:
      status_code: 400
      category: Client error
      reason: Bad Request
      message: 'Client error: (400) Bad Request'
    body:
      encoding: UTF-8
      file: no
      string: '{"errors":[{"code":"authentication_error","message":"Authenticated
        member required"}]}'
```
What am I doing wrong?
